repos:
  - repo: local
    hooks:
      - id: typecheck
        name: TypeScript typecheck
        entry: pnpm run typecheck
        language: system
        pass_filenames: false
        files: ^((src|test)/.*\.ts|package\.json|pnpm(-lock)?\.yaml|tsconfig\.json)$
      - id: test
        name: TypeScript tests
        entry: pnpm test
        language: system
        pass_filenames: false
        files: ^((src|test)/.*\.ts|package\.json|pnpm(-lock)?\.yaml|tsconfig\.json)$
